### ISSUE TITLE
Immutability (minor issue)

### ISSUE THREAD

**Issue by BertVerhees** [nedap/archie#9]
Hi Pieter, you asked for comments, so I have one.

In the CComplexObject-class I found this method: public void addAttribute(CAttribute attribute) 
Opening this functionality can cause bugs when developers are going to use it.

In my opinion this shouldn't be necessary because the AOM gets the attributes from the ADL-parser (or another parser), and only there. There may not be another way to do this. 
The only place where the class can get its attributes is in the constructor.
As you look to the ADL-Parser/AOM from Rong Chen, you see that he put much effort in keeping the code clean from mutability.

Bert

**Comment by pieterbos** [comment]
Hello Bert,

Thank you for the report.

I noticed the immutability of the original java-libs. I do not see it as a benefit and consider it to be one of the libraries drawbacks, especially when combined with the exception throwing in constructors instead of having separate validity checkers.

This makes the java-libs much harder to use: you cannot construct objects, then set fields, then validate them, you have to do it all at once using a complicated constructor with many parameters. It is also hard to create simple tools to construct reference models from archetypes plus input.
With the original java-libs, you cannot easily create a serializable version of a not yet valid model to store for the user to fix later.

With archie, all of these things are easy to do in a performant way, thanks to the mutability of objects.

Furthermore, use cases for changing the model instances exist: for the AOM this includes authoring tools or the flattener in Archie.
For the RM, updates to existing compositions can require model changes.

Builder patterns could solve this, but this means a lot of work and a lot of extra code and possible bugs. Plus more for the developer using Archie to understand.

So, all these reasons mean it is up to the user of Archie to only change the AOM/RM models when he or she means to, and to not touch setters and add-methods in all other cases.

**Comment by BertVerhees** [comment]
I understand your point, and on second thoughts is it good to have a mutable AOM.  I gonna do that too. But separate. Thanks for sharing your opinion. Inspiring.
